### ISSUE TITLE
JavaScript API for Ethereum and Stellar wallet management

### ISSUE THREAD

**Issue by davisdevs** [rate-engineering/rate3-monorepo#9]
## Simple Summary
A JS API library that provides a consistent interface to manage Ethereum and Stellar accounts through the use of respective blockchain API. Storage of data is not handled by this library.

## Motivation
The creation of demos and PoCs will most likely require blockchain account management as accounts will be used to sign transactions (move tokens, smart contracts operations, etc)

The proposed API will accelerate development as it is a single package for developers to interact with Stellar and Ethereum APIs for multichain wallet management. This reduces the overhead to understand multiple APIs to implement blockchain wallet management, a core basic functionality required in any dApp.

In the future, this can be expanded to other blockchains that Rate3 Protocol is supported on.

## Key Specifications
Unless otherwise stated, the follow specifications apply to supported blockchains:
1. Stellar
2. Ethereum

Highlighted here are key functionalities that should be supported. Other utility functions are not shown here.

### Phase 1: HD Wallet management
- [x] Able to generate fresh set of BIP39 mnemonic phrase for generation of HD wallet
- [x] Able to take in mnemonic phrase and specific account index to return the specific account
- [x] Able to send native network currency to other accounts
- [x] Able to take in account private key and perform blockchain operations on behalf
- [x] Able to integrate with Ledger and Trezor hardware wallets and perform blockchain operations on behalf
- [x] Able to encrypt/decrypt accounts according to the blockchain SDK

### Phase 2: Allow for delegated signing
- [x] Able to take in a blockchain transaction object and do delegated signing with HD wallet or private key provided
- [x] Stellar: Web authentication challenge ([SEP-0010])(https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md)

### Phase 3: Anchor-Client Bridge (Stellar [SEP-0006](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md)) 
- [x] `GET /deposit`
- [x] `GET /withdraw`
- [x] `GET /info`
- [x] `GET /transactions`

### Phase 4 Ethereum-Stellar Bridge (TBD)
- [ ] Able to take in a bifrost server URL and support the [Bifrost workflow](https://github.com/stellar/go/tree/master/services/bifrost#how-it-works) for Ethereum

### Phase 5 Decentralized Trading
- [ ] Stellar: Able to make buy/sell offers for Stellar assets on [native DEX](https://www.stellar.org/developers/guides/concepts/exchange.html)
- [ ] TBD Ethereum: Able to make buy/sell/trade offers for ERC20 assets with a decentralized liquidity provider (0x, Kyber, etc) to facilitate on-demand decentralized token trading

### Phase 6 Decentralized Identity
- [ ] Stellar: Given a human readable address format, retrieve Stellar account ID via [Stellar Federation Protocol](https://www.stellar.org/developers/guides/concepts/federation.html)
- [ ] TBD Stellar: Given a KYC object, facilitate interaction with a compliance server via [Stellar Compliance Protocol](https://www.stellar.org/developers/guides/compliance-protocol.html)

## References
https://github.com/stellar/stellar-protocol/blob/master/ecosystem
https://github.com/stellar/bifrost-js-sdk
https://github.com/ethereumjs/ethereumjs-wallet

**Comment by qianpeisheng** [comment]
**Problem**: For Stellar, the transaction history will only show the first 10 records.
**Solution**: Add parameters to the request to get more customized transaction history. 
[Ref](https://www.stellar.org/developers/horizon/reference/endpoints/operations-all.html#request)
The cursor does not include itself (in the history returned)
[UPDATE 26 OCT] This is **not** solved yet.

**Comment by qianpeisheng** [comment]
The largest part not done in my development is the integration of hardware wallet.
First, the integration of hardware wallet into `Account.js` need to redo. The proposed architecture is to create a separate `hardwareNative.js` class (or a more proper name), that holds the hardware-backed accounts (currently Ledger and Trezor); the `setAccount` method will set `account.nativeAccount` to a `hardwareNative` object, which is created prior to it, with fields denoting the brand of the hardware, and the derivation path. It will also include methods like `getAddress()`, `signTransactions()`, which basically calls respective methods in `Trezor.js` and `Ledger.js`. And the function calls in `Account.js` for hardware-backed accounts are similar to those with Stellar and Ethereum native accounts.

**Comment by qianpeisheng** [comment]
Second, some functions in `Account.js` and `WalletManager.js` do not support hardware wallet backed accounts, for example, encryption and decryption (because private keys cannot be retrieved and encrypted). There should be a `checkHardware()` method to determine if the account is using a hardware native account and handle properly when the method does not support that.

**Comment by qianpeisheng** [comment]
Third, testing for the entire hardware integration is not done, including `Trezor.js` and `Ledger.js`.

**Comment by qianpeisheng** [comment]
Next, there are some other fixes to do.
* Test case for Stellar changing trust fails
* There is currently no method to switch to other testnet or main net. 
* The infura account is my account.
* Some methods directly call the HTTP endpoints, but there may be APIs to use.
* If the test cases exceed time limit, you can extend the time limit, e,g, `jest.setTimeout(99999);` in the tests
* After the changes, the inline documentation and `JSDoc` should be updated.
* `getMultipleAccounts()` in `WalletManager.js` contains `await` inside loops, which can significantly slow the program.
